### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by stefanvermaas** [guyzmo/Arduino-Tools#1]
Hi @guyzmo,

I think you've made an pretty awesome Makefile, so cheers for that. I do have a question though; how can I make this working :)?!

This is the current state of my make file: https://gist.github.com/stefanvermaas/b5d247bf040db5b4290d. The only thing I've changed is the local lib Morse, but when I run the make command, I'm seeing this error:

``` shell
➜  MorseLib  make
# Here is the "preprocessing".
# It creates a .cpp file based with the same name as the .ino file.
# On top of the new .cpp file comes the WProgram.h header.
# At the end there is a generic main() function attached,
# plus special magic to get around the pure virtual error
# undefined reference to `__cxa_pure_virtual' from Print.o.
# Then the .cpp file will be compiled. Errors during compile will
# refer to this new, automatically generated, file.
# Not the original .ino file you actually edit...
test -d applet || mkdir applet
echo '#include "Arduino.h"' > applet/MorseLib.cpp
cat MorseLib.ino >> applet/MorseLib.cpp
echo 'extern "C" void __cxa_pure_virtual() { while (1) ; }' >> applet/MorseLib.cpp
cat /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/main.cpp >> applet/MorseLib.cpp
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -c -mmcu=atmega328p -I. -DF_CPU=16000000L  -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -Iuno.build.variant=standard/variants/standard   -IMorse/ -Os -std=c++0x -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -DARDUINO=100 applet/MorseLib.cpp -o applet/MorseLib.o
In file included from applet/MorseLib.cpp:1:
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Arduino.h:235:26: error: pins_arduino.h: No such file or directory
applet/MorseLib.cpp:2:19: error: Morse.h: No such file or directory
applet/MorseLib.cpp:4: error: 'Morse' does not name a type
applet/MorseLib.cpp: In function 'void loop()':
applet/MorseLib.cpp:9: error: 'morse' was not declared in this scope
make: *** [applet/MorseLib.o] Error 1
```

Do you've got any idea what goes wrong? Well apparently the error is the missing pin_header, but I'm not sure how to fix this. 

This is my project structure:

```
MyLib/
-- MyLib.ino
-- libraries/
---- Morse/
------ Morse.h
```

And I'm on a Mac. Could you help me make this work?

Cheers!

**Comment by guyzmo** [comment]
you either need to move the `Morse` directory into the `MyLib` directory, or change the `LOCALLIB` definition in the makefile so it is:

```
LOCALLIBS = libraries/Morse
```

**Comment by stefanvermaas** [comment]
Thanks! That kinda worked, found another error; `error: pins_arduino.h: No such file or directory`. Any idea on this? Yeah it's a missing file, but is it missing because of the build, or because I've done something wrong?

**Comment by stefanvermaas** [comment]
Any idea @guyzmo ?

**Comment by guyzmo** [comment]
oh, sorry. missed that one.

Well, the `pins_arduino.h` is that your Arduino installation is not finding the arduino variant matching the device you chose.

Is your `$(MODEL)` set up to a value existing in `make list`?

Do you have a directory within `/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/`matching your model name?
